use the health command because the path "/" isnt defined
Like obviously, it makes sense for it to be in the front end but we never actually send up that path to the backend.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -111,18 +111,18 @@ jobs:
           psql "postgres://postgres:postgres@localhost:5432/hivehand" -f004_Event_attendance.sql
 
       - name: Start Backend
-        # run: |
-        #   cd backend
-        #   npm run dev &
-        #   npx wait-on -t 120000 "http://localhost:4000"
-
         run: |
           cd backend
           npm run dev &
-          sleep 5
-          echo "Trying curl..."
-          curl -v http://localhost:4000/health || echo "curl failed"
-          npx wait-on -t 120000 "http://localhost:4000"
+          npx wait-on -t 120000 "http://localhost:4000/health"
+
+        # run: |
+        #   cd backend
+        #   npm run dev &
+        #   sleep 5
+        #   echo "Trying curl..."
+        #   curl -v http://localhost:4000/health || echo "curl failed"
+        #   npx wait-on -t 120000 "http://localhost:4000"
           
 
       - name: Start Frontend
